export const characters = [
  {
    id: `walter-white`,
    photoURL: `https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2016%2F12%2Fbreaking-bad-2000.jpg&q=60`,
    name: `Walter White`,
    fullName: `Walter Hartwell White Sr.`,
    description: `Walter Hartwell White (also known by his clandestine alias Heisenberg) (played by Bryan Cranston) is an underachieving Albuquerque, New Mexico high school chemistry teacher who, after being diagnosed with lung cancer, starts manufacturing methamphetamine to provide for his family upon his death. Knowing nothing about the drug trade, he enlists the aid of his former student, Jesse Pinkman, to sell the meth he produces. Walt's scientific knowledge and dedication to quality lead him to produce crystal meth that is purer and more potent than any competitors'. To avoid the tedious collection of pseudoephedrine required for production, Walt devises an alternative chemical process utilizing methylamine, giving his product a distinctive blue color. His crystal meth, which is given the street name "Blue Sky," dominates the market, leading to confrontations with established drug makers and dealers.`,
  },
  {
    id: `saul-goodman`,
    photoURL: `https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/streams/2013/September/130911/8C8952203-130911-ent-saulgoodman-hmed.jpg`,
    name: `Saul Goodman`,
    fullName: `James Morgan McGill`,
    description: `Saul Goodman (played by Bob Odenkirk), real name James Morgan McGill, is a sleazy lawyer who acts as Walter and Jesse's attorney and provides some of the series' comic relief. He uses the name "Saul Goodman" because he thinks his clients feel more confident with a Jewish lawyer; this name is also homophonous with the expression "[it]'s all good, man."[3] Dressing in flashy suits, Saul maintains extensive connections within the criminal underworld and serves as a go-between connecting drug distributors, evidence removers, impersonators, and other criminals-for-hire. Despite his flamboyant appearance and mannerisms—punctuated by his outrageous low-budget TV commercials—Saul is a highly competent lawyer who is able to solve problems and find loopholes in order to protect his clients. He is also reluctant to be associated with violence or murder.`,
  },
  {
    id: `hank-schrader`,
    photoURL: `https://tvline.com/wp-content/uploads/2020/02/breaking-bad-hank-dean-norris.jpg`,
    name: `Hank Schrader`,
    fullName: `Henry R. Schrader`,
    description: `Henry R. Schrader (played by Dean Norris) is Walt and Skyler's brother-in-law and Marie's husband, who works as a U.S. Drug Enforcement Administration (DEA) agent. He is involved in investigating a meth dealer known as "Heisenberg," unaware for over a year that his prey is actually Walter. Hank has a cavalier exterior, but in reality the dark side of his job affects him more than he cares to admit leading him to have anxiety attacks from post-traumatic stress. In the course of his work, Hank is promoted to El Paso, Texas from Albuquerque for a short time but experiences a traumatic event and moves back to Albuquerque. Despite his brashness, Hank is highly competent at his job and cares deeply about his family. Hank is eventually promoted to Assistant Special Agent in Charge of the DEA in Albuquerque but is still determined to solve the "Heisenberg" case, which ultimately leads to his demise.`,
  },
  {
    id: `mike-ehrmantraut`,
    photoURL: `https://carboncostume.com/wordpress/wp-content/uploads/2020/04/Mike-Ehrmantraut-from-Breaking-Bad.jpg`,
    name: `Mike Ehrmantraut`,
    fullName: `Michael Ehrmantraut`,
    description: `Michael Ehrmantraut (played by Jonathan Banks) is a former Philadelphia police officer who works for Gus—and, on occasion, Saul—as a private investigator, head of security, cleaner, and hit man. In the Better Call Saul episode "Gloves Off", it is implied that Mike is a Marine Corps veteran of the Vietnam War. While in Philadelphia, he married and had a son, Matt, who later had his own family, wife Stacey and daughter Kaylee. Mike got caught up in crooked activities within the Philadelphia police, and after Matt joined the force, he hesitated when two crooked cops approached him, so they killed him. After Matt's funeral, Mike murdered the two cops, then fled to Albuquerque to be near Stacey and Kaylee. He took a job as a parking lot attendant at the local courthouse and also performed for-hire criminal jobs on the side.`,
  },
  {
    id: `jesse-pinkman`,
    photoURL: `https://upload.wikimedia.org/wikipedia/fi/c/cc/Breaking_Bad_Jesse_Pinkman.jpg`,
    name: `Jesse Pinkman`,
    fullName: `Jesse Bruce Pinkman`,
    description: `Jesse Bruce Pinkman (played by Aaron Paul) is a small-time methamphetamine user, manufacturer, and dealer. In high school, he was an indifferent student in Walter White's chemistry class. Now in his mid-20s, Jesse is Walt's business partner in the meth trade. Jesse is impulsive, hedonistic, and uneducated beyond high school, but he is financially ambitious and streetwise. He talks in playful slang, likes to wear garish clothing that follow the latest trends in youth culture, plays video games, listens to rap and rock music, takes recreational drugs, and drives lowriders. Walt treats Jesse like a foolish son in constant need of stern correction. Jesse's own family kicked him out of their house because of his drug use. Despite the friction between them, he and Walt have a deep bond of loyalty. As a result of his relationship with Walt, Jesse becomes an excellent meth cook, ultimately leading to his exploitation by others. Despite his criminal lifestyle, Jesse is far more empathetic than Walt. He is horrified by the brutality at the higher levels of the drug trade particularly during later seasons, but remains involved with Walt out of necessity. He is very protective of children; his desire to keep children out of the violent drug world gives rise to several key events throughout the series. He wrestles with feelings of guilt about the deaths, all drug-related, of people he has been associated with. Towards the end of the fifth season he is overwhelmed by guilt and his "blood money." Realizing how much pain he has caused for money leads him to attempt to give bundles of cash from his final payoff to people he knows and then throw them from his car window onto random lawns and porches. In El Camino: A Breaking Bad Movie, Jesse departs for a new life in Alaska.`,
  },
  {
    id: `gus-fring`,
    photoURL: `https://i.insider.com/62508d8fee61990018ddda8a?width=1136&format=jpeg`,
    name: `Gus Fring`,
    fullName: `Gustavo Fring`,
    description: `Gustavo Fring (played by Giancarlo Esposito) is the Chilean-born proprietor of Los Pollos Hermanos, a highly successful fried chicken restaurant chain. He is also a public booster for the local DEA office and a member of the hospital board. Despite outward appearances, Gus is a major drug kingpin initially affiliated with the Mexican drug cartel in Ciudad Juárez, who use his restaurants as a front for methamphetamine distribution throughout the American southwest, supported by Los Pollos' corporate owners, Madrigal Electromotive. Like Walter White, Gus is a criminal who "hides in plain sight," using his anti-drug philanthropy to conceal his true nature.`,
  },
  {
    id: `skyler-white`,
    photoURL: `https://inthesetimes.com/imager/s3_us-east-2_amazonaws_com/itt-images/Beyerstein_Doyle_Breaking_Bad_Skyler_White_01c8ac7cc3b849e525e370bc51344120.jpg`,
    name: `Skyler White`,
    fullName: `Skyler White (née Lambert)`,
    description: `Skyler White (née Lambert) (played by Anna Gunn) is Walter's wife. She has had several meager sources of income: writing short stories, selling items on eBay, working as a bookkeeper, and ultimately helping her husband launder money. Skyler and Walter have a son, Walter Jr., and an infant daughter, Holly. Skyler loves Walter very much, but their marriage becomes increasingly strained due to his unexplained absences and bizarre behavior, ultimately leading to their separation. Later, once Walter reveals his operation, she aids him in laundering his funds. They buy the car wash where Walter had recently moonlighted. Although she helps Walter, she remains deeply unhappy with the overall situation. As Walter slowly becomes more of a "hardened criminal," her emotions of fear and worry for him become increasingly prevalent. When in the episode "Buried," Skyler's DEA brother-in-law Hank tells her he is on to Walt but needs her help to provide sufficient evidence to build a successful case, Skyler replies that she needs a lawyer and later tells Walt they should remain quiet. In the episode "Breaking Bad" of Better Call Saul, she is mentioned to have gotten a plea deal with the prosecutors.`,
  },
  {
    id: `todd-alquist`,
    photoURL: `https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/10/breaking-bad-todd.jpg`,
    name: `Todd Alquist`,
    fullName: `Todd Alquist`,
    description: `Todd Alquist (played by Jesse Plemons) is an exterminator for Vamonos Pest, a fumigation company used by Walt, Mike, and Jesse as the front for their meth business after Gus Fring's death. Todd and the other Vamonos employees are also burglars, gathering information from the houses they tent and selling it to outside parties. Todd notices and disables a nanny cam at Walt and Jesse's first post-Gus Fring cook site, attracting their attention as someone they think might be useful in the future. He aids in the heist of methylamine from a freight train, and gives a friendly wave to a boy who stumbles on the crime scene, but then shoots him without warning. The team reluctantly keeps Todd employed after the murder, accepting his explanation that he assumed there could be no witnesses to the crime and they all risked arrest. Todd's explanation, plus his claims that his uncle (Jack Welker) runs a gang with connections that could be valuable to the meth operation, convince Walt and Mike to keep him alive, although Jesse is reluctant.`,
  },
  {
    id: `marie-schrader`,
    photoURL: `https://www.meugamer.com/wp-content/uploads/2022/08/marie_schrader_better_call_saul.jpg`,
    name: `Marie Schrader`,
    fullName: `Marie Schrader (née Lambert)`,
    description: `Marie Schrader (née Lambert) (played by Betsy Brandt) is Skyler's sister, Hank's wife, and Walt's sister-in-law. Marie works as a radiologic technologist. She does not hesitate to offer advice to others but often fails to practice what she preaches. She shoplifts compulsively—apparently a manifest symptom of kleptomania—a behavior for which she sees a therapist. She appears self-centered and shallow but cares deeply for her husband and her sister's family. Nearly all of her household and clothing items are shades of the color purple.`,
  },
  {
    id: `lalo-salamanca`,
    photoURL: `https://www.tvinsider.com/wp-content/uploads/2022/04/better-call-saul-season-6-tony-dalton-lalo.jpg`,
    name: `Lalo Salamanca`,
    fullName: `Eduardo "Lalo" Salamanca`,
    description: `Eduardo "Lalo" Salamanca (portrayed by Tony Dalton) is another of Hector's nephews, introduced in season 4 of Better Call Saul. He arrives from Mexico soon after Hector's stroke to help run the family's drug operation, and takes a greater interest in the day-to-day details than Hector did, which makes Nacho uneasy. Lalo visits Hector in the nursing home and enables Hector to communicate more effectively by giving him a front desk call bell, which Lalo kept as a souvenir after Hector killed a hotelier. Lalo thanks Gus for giving Hector first aid after his stroke and paying for his care, but also surveils Gus' subordinates in order to learn their regular activities. When Werner escapes from Mike's supervision, Lalo follows Mike and kills Fred, a money wire store clerk, to obtain Werner's location. He becomes aware that Werner was constructing something for Gus and Gus fabricates a story to explain events of which Lalo is aware, which Lalo outwardly accepts while remaining suspicious.`,
  },
];
